import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { assessProcess, createProofManifest, demoClaims, demoInstitution, demoProcess, sha256Hex, verifyProof } from '@polis/domain';
export type Route = { method:string; path:string; handler:(req:IncomingMessage, body:unknown)=>Promise<unknown>|unknown };
const json=(res:ServerResponse, status:number, value:unknown)=>{ const text=JSON.stringify(value); res.writeHead(status,{ 'content-type':'application/json; charset=utf-8', 'content-length':Buffer.byteLength(text), 'access-control-allow-origin':'*' }); res.end(text); };
const readBody=(req:IncomingMessage)=>new Promise<unknown>((resolve,reject)=>{ let data=''; req.on('data',(c:Buffer)=>{data+=c.toString('utf8'); if(data.length>5_000_000){ reject(new Error('body too large')); req.destroy(); }}); req.on('end',()=>{ if(!data) resolve({}); else { try{resolve(JSON.parse(data));}catch{resolve({ raw:data });} } }); req.on('error',reject); });
export function defaultRoutes(service:string): Route[] { return [
 {method:'GET',path:'/healthz',handler:()=>({status:'ok',service})}, {method:'GET',path:'/readyz',handler:()=>({status:'ready',service})}, {method:'GET',path:'/metrics',handler:()=>`polis_service_up{service="${service}"} 1\n`}, {method:'GET',path:'/version',handler:()=>({service,version:'0.1.0-v1',gitSha:process.env.GIT_SHA ?? 'dev'})},
 {method:'GET',path:'/api/v1/governance/institutions',handler:()=>({items:[demoInstitution]})}, {method:'GET',path:'/api/v1/governance/processes',handler:()=>({items:[demoProcess]})}, {method:'GET',path:'/api/v1/evidence/claims',handler:()=>({items:demoClaims})},
 {method:'GET',path:'/api/v1/assessment/process-public-complaint',handler:()=>assessProcess(demoProcess)}, {method:'POST',path:'/api/v1/proofs',handler:async(_req,body)=>createProofManifest(String((body as {content?:string}).content ?? ''),(body as {visibility?:never}).visibility)},
 {method:'POST',path:'/api/v1/verify/hash',handler:async(_req,body)=>{ const content=String((body as {content?:string}).content ?? ''); const manifest=await createProofManifest(content); return verifyProof(manifest, await sha256Hex(content));}},
 {method:'GET',path:'/api/v1/polis/conversations',handler:()=>({items:[{id:'conv-public-complaints',topic:'How should public complaints become traceable?',clusters:3,consensus:['Citizens need a receipt','Appeals must be visible','Private data must stay private']}]} )},
 {method:'POST',path:'/api/v1/ai/explain',handler:(_req,body)=>({answer:`Source-linked explanation for: ${String((body as {question?:string}).question ?? 'governance process')}`, citations:demoClaims.map(c=>c.evidence[0]), model:'mock-civic-chat-v1', reviewState:'under_review'})},
 {method:'GET',path:'/api/v1/rewards/rules',handler:()=>({rewarded:['evidence contribution','review','translation','accessibility work','bug report'], neverRewarded:['political agreement','vote choice','consensus outcome']})},
 {method:'GET',path:'/api/v1/audit/events',handler:()=>({items:[{id:'audit-demo',service,action:'service.started',subjectId:service,visibility:'public',createdAt:new Date(0).toISOString(),redacted:false}]})}
 ]; }
export function startService(service:string, port:number, extra:Route[]=[]){ const routes=[...defaultRoutes(service),...extra]; const server=createServer(async(req,res)=>{ if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'}); return res.end();} const url=new URL(req.url ?? '/', 'http://localhost'); const route=routes.find(r=>r.method===req.method && r.path===url.pathname); if(!route) return json(res,404,{error:'not_found',service,path:url.pathname}); try{ const body=req.method==='GET'?{}:await readBody(req); const out=await route.handler(req,body); if(typeof out==='string'){res.writeHead(200,{'content-type':url.pathname==='/metrics'?'text/plain; charset=utf-8':'text/plain; charset=utf-8'}); return res.end(out);} return json(res,200,out);} catch(error){return json(res,500,{error:error instanceof Error?error.message:'unknown'});} }); server.listen(port); return server; }
